### ISSUE TITLE
BUG: data.inputPath is undefined within computed function (v1.1.0-rc1) 

### ISSUE THREAD

**Issue by xplosionmind** [photogabble/eleventy-plugin-interlinker#28]
Hi! I am testing v1.1.0-rc. I got an error during build time. I am sharing [here](https://paste.yunohost.org/raw/usoruvoziq) the debug log, hoping it could help.

**Comment by carbontwelve** [comment]
Thankyou for the report, do you know if you're using the embed functionality via the syntax `![[slug]]`?

**Comment by carbontwelve** [comment]
Interesting, I had assumed that all objects within the 11ty all collection refered to a file that had been read from disk and thus has an `inputPath`. I'll be working on this bug today.

```
[11ty] Cannot read properties of undefined (reading 'inputPath') (via TypeError)
2024-05-02T07:53:20.061Z Eleventy:EleventyErrorHandler (error stack): TypeError: Cannot read properties of undefined (reading 'inputPath')
    at Interlinker.compute (/home/tommi/tommi.space/node_modules/@photogabble/eleventy-plugin-interlinker/src/interlinker.js:100:43)
    at Object.outboundLinks (/home/tommi/tommi.space/node_modules/@photogabble/eleventy-plugin-interlinker/index.js:66:54)
    at ComputedData._setupDataEntry (/home/tommi/tommi.space/node_modules/.pnpm/@11ty+eleventy@2.0.1/node_modules/@11ty/eleventy/src/ComputedData.js:90:25)
    at ComputedData.processRemainingData (/home/tommi/tommi.space/node_modules/.pnpm/@11ty+eleventy@2.0.1/node_modules/@11ty/eleventy/src/ComputedData.js:111:16)
    at Template.resolveRemainingComputedData (/home/tommi/tommi.space/node_modules/.pnpm/@11ty+eleventy@2.0.1/node_modules/@11ty/eleventy/src/Template.js:625:31)
    at TemplateMap.resolveRemainingComputedData (/home/tommi/tommi.space/node_modules/.pnpm/@11ty+eleventy@2.0.1/node_modules/@11ty/eleventy/src/TemplateMap.js:735:39)
    at TemplateMap.cache (/home/tommi/tommi.space/node_modules/.pnpm/@11ty+eleventy@2.0.1/node_modules/@11ty/eleventy/src/TemplateMap.js:463:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TemplateWriter._createTemplateMap (/home/tommi/tommi.space/node_modules/.pnpm/@11ty+eleventy@2.0.1/node_modules/@11ty/eleventy/src/TemplateWriter.js:330:5)
    at async TemplateWriter.generateTemplates (/home/tommi/tommi.space/node_modules/.pnpm/@11ty+eleventy@2.0.1/node_modules/@11ty/eleventy/src/TemplateWriter.js:360:5)
```

**Comment by xplosionmind** [comment]
> Thankyou for the report, do you know if you're using the embed functionality via the syntax `![[slug]]`?

AFAIK, I use the `![[Non-Slugged title bla bla]]` syntax, both for embeds and for regular wikilinks.

**Comment by xplosionmind** [comment]
> I’ll be working on this bug today.

Wonderful, thank you! Please tell me if there is any further testing I can help with.
