### ISSUE TITLE
BUG: unable to render embed template (v1.1.0-rc2)

### ISSUE THREAD

**Issue by carbontwelve** [photogabble/eleventy-plugin-interlinker#31]
```
[11ty] (unknown path) [Line 1, Column 4]
[11ty]   unknown block tag: layout (via Template render error)
[11ty] 
[11ty] Original error stack trace: Template render error: (unknown path) [Line 1, Column 4]
[11ty]   unknown block tag: layout
[11ty]     at Object._prettifyError (/Users/simon/Code/photogabble/website/node_modules/nunjucks/src/lib.js:32:11)
[11ty]     at Template.init (/Users/simon/Code/photogabble/website/node_modules/nunjucks/src/environment.js:416:19)
[11ty]     at Template.Obj (/Users/simon/Code/photogabble/website/node_modules/nunjucks/src/object.js:51:15)
[11ty]     at new Template (/Users/simon/Code/photogabble/website/node_modules/nunjucks/src/environment.js:390:18)
[11ty]     at Nunjucks.compile (/Users/simon/Code/photogabble/website/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:404:14)
[11ty]     at TemplateRender.getCompiledTemplate (/Users/simon/Code/photogabble/website/node_modules/@11ty/eleventy/src/TemplateRender.js:278:26)
[11ty]     at compile (/Users/simon/Code/photogabble/website/node_modules/@11ty/eleventy/src/Plugins/RenderPlugin.js:43:13)
[11ty]     at RenderManager.compile (/Users/simon/Code/photogabble/website/node_modules/@11ty/eleventy/src/Plugins/RenderPlugin.js:389:12)
[11ty]     at Interlinker.compileTemplate (/Users/simon/Code/photogabble/website/node_modules/@photogabble/eleventy-plugin-interlinker/src/interlinker.js:61:30)
[11ty]     at /Users/simon/Code/photogabble/website/node_modules/@photogabble/eleventy-plugin-interlinker/src/interlinker.js:153:37

```

**Comment by carbontwelve** [comment]
Upon investigation the cause is trying to embed a file that doesn't exist. Due to my refactoring the plugin is attempting to embed the stub file into the page with the incorrect template language selected.

This is a regression, if a page can't be found, it can't be embedded.

**Comment by carbontwelve** [comment]
Regression caused by splitting on `#` for `<a id="..."/>` linking
<img width="918" alt="image" src="https://github.com/photogabble/eleventy-plugin-interlinker/assets/464699/c54c6644-cf8c-4095-ae83-61b8fa661a09">

**Comment by carbontwelve** [comment]
Ah-ha! Looks like Obsidian get around this by stopping you from having certain characters in page titles.

<img width="638" alt="image" src="https://github.com/photogabble/eleventy-plugin-interlinker/assets/464699/3fa4595d-c977-4f1b-9fab-58de7721a48a">
