### ISSUE TITLE
CRASH: change to wikilink embed reference with 11ty in serve mode results in crash

### ISSUE THREAD

**Issue by carbontwelve** [photogabble/eleventy-plugin-interlinker#33]
When running 11ty in serve mode and making a change to a wikilink reference that prompts a rebuild the entire process crashes.

```
[11ty] Cannot read properties of undefined (reading 'compileOptions') (via TypeError)
[11ty] 
[11ty] Original error stack trace: TypeError: Cannot read properties of undefined (reading 'compileOptions')
[11ty]     at CustomEngine.shouldSpiderJavaScriptDependencies (/Users/simon/Code/photogabble/website/node_modules/@11ty/eleventy/src/Engines/Custom.js:289:13)
[11ty]     at EleventyExtensionMap.shouldSpiderJavaScriptDependencies (/Users/simon/Code/photogabble/website/node_modules/@11ty/eleventy/src/EleventyExtensionMap.js:130:32)
[11ty]     at /Users/simon/Code/photogabble/website/node_modules/@11ty/eleventy/src/EleventyFiles.js:343:27
[11ty]     at Array.filter (<anonymous>)
[11ty]     at EleventyFiles.getWatchPathCache (/Users/simon/Code/photogabble/website/node_modules/@11ty/eleventy/src/EleventyFiles.js:340:27)
[11ty]     at Eleventy._initWatchDependencies (/Users/simon/Code/photogabble/website/node_modules/@11ty/eleventy/src/Eleventy.js:940:44)
[11ty]     at Eleventy._watch (/Users/simon/Code/photogabble/website/node_modules/@11ty/eleventy/src/Eleventy.js:833:16)
[11ty]     at async watchRun (/Users/simon/Code/photogabble/website/node_modules/@11ty/eleventy/src/Eleventy.js:1047:9)
[11ty]     at async FSWatcher.<anonymous> (/Users/simon/Code/photogabble/website/node_modules/@11ty/eleventy/src/Eleventy.js:1065:7)
```

To clarify, this was when I was loading `![[ Building a self-contained game in C# under 2 kilobytes ]]` resulting in a broken embed, when I amended it to escape the `#` the above crash happened during rebuild.

**Comment by carbontwelve** [comment]
#34 didn't fix the issue, this seems to be an internal issue with the `RenderManager` class internal to 11ty.
Within the Render Plugin it will ignore `templateConfig` passed through to the `compile` function and set it from `this`: [see source](https://github.com/11ty/eleventy/blob/7ee3bf53854173c1d6aaff955eeb9a3a39191f04/src/Plugins/RenderPlugin.js#L431).

This works the first time 11ty builds, but subsequent builds with `--watch` cause the issue. I have been able to fix this in my website by modifying the interlinker plugin with the following:

```js
  eleventyConfig.on("eleventy.config", (cfg) => {
    interlinker.templateConfig = cfg;
    if (interlinker.rm) interlinker.rm.templateConfig = cfg;
  });
```

This ensures that the `RenderManager` is using the current template config.
